rm: cannot remove 'time.csv': No such file or directory
rm: cannot remove 'final_phi.csv': No such file or directory
rm: cannot remove 'phi_128.png': No such file or directory
npwg = 10 np = 8 nwg = 18
npwg = 10 np = 8 nwg = 18
[adroit-16:198211:0:198211] Caught signal 11 (Segmentation fault: address not mapped to object at address 0xffffff87)
==== backtrace (tid: 198211) ====
 0  /lib64/libucs.so.0(ucs_handle_error+0x2a4) [0x14ae6915b2a4]
 1  /lib64/libucs.so.0(+0x2347c) [0x14ae6915b47c]
 2  /lib64/libucs.so.0(+0x2364a) [0x14ae6915b64a]
 3  /lib64/libuct.so.0(+0x20064) [0x14ae695b7064]
 4  /lib64/libucs.so.0(ucs_conn_match_get_elem+0x81) [0x14ae69157bd1]
 5  /lib64/libuct.so.0(uct_tcp_cm_get_ep+0x5d) [0x14ae695b714d]
 6  /lib64/libuct.so.0(+0x204dc) [0x14ae695b74dc]
 7  /lib64/libuct.so.0(+0x1c32c) [0x14ae695b332c]
 8  /lib64/libuct.so.0(+0x1e25c) [0x14ae695b525c]
 9  /lib64/libucs.so.0(ucs_event_set_wait+0xf1) [0x14ae691600b1]
10  /lib64/libuct.so.0(uct_tcp_iface_progress+0x7b) [0x14ae695b530b]
11  /lib64/libucp.so.0(ucp_worker_progress+0x2a) [0x14ae697fabea]
12  /usr/local/openmpi/4.1.0/gcc/lib64/openmpi/mca_pml_ucx.so(mca_pml_ucx_recv+0x100) [0x14ae69c577f0]
13  /usr/local/openmpi/4.1.0/gcc/lib64/libmpi.so.40(MPI_Recv+0x145) [0x14ae787ce875]
14  ./a.out() [0x4099f6]
15  /usr/lib64/libc.so.6(__libc_start_main+0xf3) [0x14ae7785d493]
16  ./a.out() [0x408c2e]
=================================
[adroit-16:198211] *** Process received signal ***
[adroit-16:198211] Signal: Segmentation fault (11)
[adroit-16:198211] Signal code:  (-6)
[adroit-16:198211] Failing at address: 0x2557c00030643
[adroit-16:198211] [ 0] /usr/lib64/libpthread.so.0(+0x12c20)[0x14ae77c11c20]
[adroit-16:198211] [ 1] /lib64/libuct.so.0(+0x20064)[0x14ae695b7064]
[adroit-16:198211] [ 2] /lib64/libucs.so.0(ucs_conn_match_get_elem+0x81)[0x14ae69157bd1]
[adroit-16:198211] [ 3] /lib64/libuct.so.0(uct_tcp_cm_get_ep+0x5d)[0x14ae695b714d]
[adroit-16:198211] [ 4] /lib64/libuct.so.0(+0x204dc)[0x14ae695b74dc]
[adroit-16:198211] [ 5] /lib64/libuct.so.0(+0x1c32c)[0x14ae695b332c]
[adroit-16:198211] [ 6] /lib64/libuct.so.0(+0x1e25c)[0x14ae695b525c]
[adroit-16:198211] [ 7] /lib64/libucs.so.0(ucs_event_set_wait+0xf1)[0x14ae691600b1]
[adroit-16:198211] [ 8] /lib64/libuct.so.0(uct_tcp_iface_progress+0x7b)[0x14ae695b530b]
[adroit-16:198211] [ 9] /lib64/libucp.so.0(ucp_worker_progress+0x2a)[0x14ae697fabea]
[adroit-16:198211] [10] /usr/local/openmpi/4.1.0/gcc/lib64/openmpi/mca_pml_ucx.so(mca_pml_ucx_recv+0x100)[0x14ae69c577f0]
[adroit-16:198211] [11] /usr/local/openmpi/4.1.0/gcc/lib64/libmpi.so.40(MPI_Recv+0x145)[0x14ae787ce875]
[adroit-16:198211] [12] ./a.out[0x4099f6]
[adroit-16:198211] [13] /usr/lib64/libc.so.6(__libc_start_main+0xf3)[0x14ae7785d493]
[adroit-16:198211] [14] ./a.out[0x408c2e]
[adroit-16:198211] *** End of error message ***
I, thread: 0am sending rows: 18 through 36 to thread 1
I, thread: 0received from thread: 1
I, thread: 1 am sending rows: 144 through 162 to thread 0
[1645733226.664293] [adroit-16:198210:0]         tcp_ep.c:1044 UCX  ERROR tcp_ep 0x1beffc0 (state=CONNECTED): recv(35) failed: Connection reset by remote peer
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 198211 on node adroit-16 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
Loading required package: ggplot2
Error in file(file, "rt") : cannot open the connection
Calls: read.csv -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'final_phi.csv': No such file or directory
Execution halted
